feat: save filter on local storage
acikkaynak/afet-destek-org pull request #184
Opened 2023-02-11 12:38 UTC by adnanjpg

closes https://github.com/acikkaynak/afet-destek-org/issues/171

2023-02-11 14:18 UTC, easeccy commented on lib/pages/demands_page/state/demands_state.dart
> +@HiveType(typeId: 0)
Use `shared_preferences` instead.

2023-02-11 14:18 UTC, easeccy requested changes
Fixes needed.

2023-02-11 23:08 UTC, adnanjpg commented on lib/pages/demands_page/state/demands_cubit.dart
> +  static const String _filterKey = 'demands_filter';
filterKey = 'filterKey'

2023-02-11 23:08 UTC, adnanjpg commented on lib/pages/demands_page/state/demands_cubit.dart
> +  Future<void> initFilterState() async {
convert to init, await and try catch initing filter, then fetch demands, remove getDemands

2023-02-11 23:09 UTC, adnanjpg commented on lib/pages/demands_page/state/demands_cubit.dart
> +    unawaited(
try catch

2023-02-11 23:10 UTC, adnanjpg commented on lib/pages/demands_page/state/demands_state.dart
> +    DemandsStateFilter? filter,
non nullable, required, defualt .empty

2023-02-11 23:10 UTC, adnanjpg commented on lib/pages/demands_page/state/demands_state.dart
> +  factory DemandsState({
const

2023-02-11 23:11 UTC, adnanjpg commented on lib/pages/demands_page/state/demands_state.dart
> +class DemandsStateFilter with _$DemandsStateFilter {
const

2023-02-12 09:43 UTC, easeccy commented on lib/pages/demands_page/state/demands_cubit.dart
> +    unawaited(
No need, this is unawaited, won't block the next line on error. But remove the bang and make it non-nullable.

2023-02-12 18:33 UTC, adnanjpg commented
changes done, please review @easeccy

2023-02-13 06:25 UTC, easeccy approved these changes

2023-02-13 06:26 UTC, easeccy commented
Looks great, thanks.

2023-02-13 06:26 UTC, merged